version: '3'
services:
  consul:
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"

  vault:
    image: hashicorp/vault:latest
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root-token
